 package com.ndlan.canyin.core.common;
 
 import com.ndlan.canyin.core.utils.EnumUtil;
import com.ndlan.canyin.core.common.AuthEnum;
import com.ndlan.canyin.core.common.BackupIntervalEnum;
import com.ndlan.canyin.core.common.BillOpTypeEnum;
import com.ndlan.canyin.core.common.BillPlaceEnterPageEnum;
import com.ndlan.canyin.core.common.BillStatusEnum;
import com.ndlan.canyin.core.common.BillTypeEnum;
import com.ndlan.canyin.core.common.BuffetTypeEnum;
import com.ndlan.canyin.core.common.BussLogActEnum;
import com.ndlan.canyin.core.common.BussLogTypeEnum;
import com.ndlan.canyin.core.common.CamLevelEnum;
import com.ndlan.canyin.core.common.CardOperationTypeEnum;
import com.ndlan.canyin.core.common.CreditStatusEnum;
import com.ndlan.canyin.core.common.DataLogActEnum;
import com.ndlan.canyin.core.common.DataLogTypeEnum;
import com.ndlan.canyin.core.common.DiningEnvEnum;
import com.ndlan.canyin.core.common.DinnerStatusEnum;
import com.ndlan.canyin.core.common.DiscountTypeEnum;
import com.ndlan.canyin.core.common.DishesStatusEnum;
import com.ndlan.canyin.core.common.EmpOpTypeEnum;
import com.ndlan.canyin.core.common.EnableStatusEnum;
import com.ndlan.canyin.core.common.ForeignCategoryEnum;
import com.ndlan.canyin.core.common.GenderEnum;
import com.ndlan.canyin.core.common.JobStatusEnum;
import com.ndlan.canyin.core.common.MemberCardStatusEnum;
import com.ndlan.canyin.core.common.MemberEduEnum;
import com.ndlan.canyin.core.common.MemberWorkEnum;
import com.ndlan.canyin.core.common.MolingModeEnum;
import com.ndlan.canyin.core.common.MsgStatusEnum;
import com.ndlan.canyin.core.common.MsgTypeEnum;
import com.ndlan.canyin.core.common.OcsStatusEnum;
import com.ndlan.canyin.core.common.OcsTypeEnum;
import com.ndlan.canyin.core.common.OcsrStatusEnum;
import com.ndlan.canyin.core.common.OrderStatusEnum;
import com.ndlan.canyin.core.common.OrderWayEnum;
import com.ndlan.canyin.core.common.PaymentTypeEnum;
import com.ndlan.canyin.core.common.PicTypeEnum;
import com.ndlan.canyin.core.common.PrinterModeEnum;
import com.ndlan.canyin.core.common.PrinterTypeEnum;
import com.ndlan.canyin.core.common.PungentLevelEnum;
import com.ndlan.canyin.core.common.RegOriginEunm;
import com.ndlan.canyin.core.common.RegionDivEnum;
import com.ndlan.canyin.core.common.RoleTypeEnum;
import com.ndlan.canyin.core.common.SeviceChargeTypeEnum;
import com.ndlan.canyin.core.common.SpecialEnvEnum;
import com.ndlan.canyin.core.common.SpecialReasonTypeEnum;
import com.ndlan.canyin.core.common.SpecialStyleEnum;
import com.ndlan.canyin.core.common.SysDataTypeEnum;
import com.ndlan.canyin.core.common.SysLogTypeEnum;
import com.ndlan.canyin.core.common.TabBillTypeEnum;
import com.ndlan.canyin.core.common.TerminalDivEnum;
import com.ndlan.canyin.core.common.TerminalTypeEnum;
import com.ndlan.canyin.core.common.TrueFalseEnum;
import com.ndlan.canyin.core.common.VisitTypeEnum;
import com.ndlan.canyin.core.common.WorkStationConEnum;
import com.ndlan.canyin.core.common.WorkStationStatusEnum;
import java.io.IOException;
 
 public class GenerateEnumSQL
 {
   public static void main(String[] args)
     throws IOException
   {
     EnumUtil.deleteAll();
     BackupIntervalEnum.generateSQL();
     BillOpTypeEnum.generateSQL();
     BillStatusEnum.generateSQL();
     BussLogActEnum.generateSQL();
     BussLogTypeEnum.generateSQL();
     CamLevelEnum.generateSQL();
     CardOperationTypeEnum.generateSQL();
     CreditStatusEnum.generateSQL();
     DataLogActEnum.generateSQL();
     DataLogTypeEnum.generateSQL();
     DiningEnvEnum.generateSQL();
     DinnerStatusEnum.generateSQL();
     DiscountTypeEnum.generateSQL();
     DishesStatusEnum.generateSQL();
     EmpOpTypeEnum.generateSQL();
     EnableStatusEnum.generateSQL();
     ForeignCategoryEnum.generateSQL();
     GenderEnum.generateSQL();
     JobStatusEnum.generateSQL();
     MemberCardStatusEnum.generateSQL();
     MemberEduEnum.generateSQL();
     MemberWorkEnum.generateSQL();
     MolingModeEnum.generateSQL();
     MsgStatusEnum.generateSQL();
     MsgTypeEnum.generateSQL();
     OcsrStatusEnum.generateSQL();
     OcsStatusEnum.generateSQL();
     OcsTypeEnum.generateSQL();
     OrderStatusEnum.generateSQL();
     OrderWayEnum.generateSQL();
     PaymentTypeEnum.generateSQL();
     PicTypeEnum.generateSQL();
     RegionDivEnum.generateSQL();
     RegOriginEunm.generateSQL();
     SeviceChargeTypeEnum.generateSQL();
     SpecialEnvEnum.generateSQL();
     SpecialReasonTypeEnum.generateSQL();
     SpecialStyleEnum.generateSQL();
     SysDataTypeEnum.generateSQL();
     SysLogTypeEnum.generateSQL();
     TabBillTypeEnum.generateSQL();
     TerminalDivEnum.generateSQL();
     TerminalTypeEnum.generateSQL();
     TrueFalseEnum.generateSQL();
     VisitTypeEnum.generateSQL();
     WorkStationConEnum.generateSQL();
     WorkStationStatusEnum.generateSQL();
     PrinterModeEnum.generateSQL();
     PrinterTypeEnum.generateSQL();
     PungentLevelEnum.generateSQL();
     BillTypeEnum.generateSQL();
     AuthEnum.generateSQL();
     RoleTypeEnum.generateSQL();
 
     BillPlaceEnterPageEnum.generateSQL();
     BuffetTypeEnum.generateSQL();
   }
 }

